apiVersion: v1
kind: ConfigMap
metadata:
  name: tirocinio-smart-config
  namespace: tirocinio-smart
data:
  DB_ENGINE: "django.db.backends.mysql"
  DB_HOST: "db-service.general.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "tirocinio-smart"
  DB_USER: "tirociniosmart_db_user"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_TIME: "86400"
  JWT_ISSUER: "tirocinio-smart"
  MAX_WAIT_SECONDS_ENTRYPOINT: "60"
  SERVICE_PORT: "8000"
  NAMESPACE: "tirocinio-smart"
