apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: zookeeper
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_NUM_PARTITIONS: "2"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service.zookeeper.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_MIN_INSYNC_REPLICAS: "2"