apiVersion: apps/v1
kind: Deployment
metadata:
  name: tirocinio-smart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tirocinio-smart
  template:
    metadata:
      labels:
        app: tirocinio-smart
    spec:
      containers:
        - name: tirocinio-smart
          image: docker.io/antoniobasileo/tirocinio-smart-app:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: tirocinio-smart-config
            - secretRef:
                name: tirocinio-smart-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
