apiVersion: v1
kind: ConfigMap
metadata:
  name: manage-orders-config
  namespace: manage-orders
data:
  application-remote.yaml: |
    manage-orders:
        environment: test
        
    jwt:
      secret: ${JWT_SECRET_KEY}
  
    spring:
      datasource:
        username: manage_orders_user
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://db-service.general.svc.cluster.local:3306/manage-orders?allowPublicKeyRetrieval=true&useSSL=false
      jpa:
        properties:
          hibernate:
            default_schema: manage-orders
            show_sql: false
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
      kafka:
        bootstrap-servers: kafka-service.zookeeper.svc.cluster.local:9092
        consumer:
          topic: topic-orders
          group-id: manage-orders
      liquibase:
        enabled: true
        changelog: config/liquibase/master.xml
        schema: manage-orders
  
    logging:
      level:
        root: INFO
  
    server:
      port: 8080
      servlet:
        context-path: /manage-orders
