apiVersion: v1
kind: ConfigMap
metadata:
  name: eoq-config
  namespace: eoq
data:
  DB_ENGINE: "django.db.backends.mysql"
  DB_HOST: "db-service.general.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "eoq"
  DB_USER: "eoq_user"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_TIME: "86400"
  JWT_ISSUER: "eoq"
  MAX_WAIT_SECONDS_ENTRYPOINT: "60"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.zookeeper.svc.cluster.local:9092"
  KAFKA_TOPIC: "eoq"
  KAFKA_GROUP_ID: "eoq"
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  KAFKA_ENABLE_AUTO_COMMIT: "true"
  KAFKA_ACKS: "all"
  KAFKA_RETRIES: "10"
  KAFKA_LINGER_MS: "10"
  KAFKA_COMPRESSION_TYPE: "gzip"
  KAFKA_MAX_POLL_RECORDS: "100"
  KAFKA_CONSUMER_TIMEOUT_MS: "30000"
