apiVersion: apps/v1
kind: Deployment
metadata:
  name: eoq
  namespace: eoq
  labels:
    app: eoq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eoq
  template:
    metadata:
      labels:
        app: eoq
    spec:
      containers:
      - name: eoq
        image: docker.io/antoniobasileo/eoq-app:latest
        ports:
          - containerPort: 8000
            protocol: TCP
        envFrom:
          - configMapRef:
              name: eoq-config
          - secretRef:
              name: eoq-secrets
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"

